server:
  port: ${POST_SERVICE_PORT:8083}
  servlet:
    context-path: /post

spring:
  application:
    name: post-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      uri: ${POST_MONGODB_URI:mongodb://root:root@localhost:27017/post-service?authSource=admin}

app:
  services:
    identity: ${IDENTITY_SERVICE_BASE_URL:http://localhost:8080/identity}
    profile: ${PROFILE_SERVICE_BASE_URL:http://localhost:8081/profile}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
